train_data: "data/cs-training.csv"
test_data: "data/cs-test.csv"

model: XGBoost # XGBoost or RandomForestClassifier

XGBoost:
    learning_rate: 0.05
    max_features: 'sqrt'
    random_state: 10
    n_estimators: 70
    max_depth: 7
    min_samples_split: 600
    min_samples_leaf: 50
    subsample: 0.8

RandomForestClassifier:
    n_estimators: 100
    criterion: 'gini'
    max_depth: 100
    min_samples_split: 2
    min_samples_leaf: 1

model_saved_path: "models/XGBoost.sav"
output_path: "output/submission.csv"
